[package]
name = "jgsms-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smsgg-core = { path = "../smsgg-core" }

clap = { version = "4", features = ["derive"] }
env_logger = "0.10"