[package]
name = "z80-emu"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
bincode = ["dep:bincode"]

[dependencies]
jgenesis-common = { path = "../../jgenesis-common" }

bincode = { workspace = true, optional = true }
log = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
