[package]
name = "z80-test-runner"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z80-emu = { path = "../z80-emu" }

env_logger = { workspace = true }

[lints]
workspace = true
